language: elixir
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
  - MIX_ENV=test
elixir:
  - 1.8.0
otp_release:
  - 21.2
cache:
  directories:
    - deps
    - _build/
branches:
  only:
  - master
install:
  - sudo -u postgres psql -p 5433 -c "create user challenge_gov with superuser password 'password';"
  - cp .travis/test.extra.exs config/test.extra.exs
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - mix compile
  - mix do ecto.create, ecto.migrate
script:
  - mix compile --force --warnings-as-errors
  - mix format --check-formatted
  - mix credo
  - mix test
